[package]
name = "lib-bdd-ffi"
version = "0.1.0"
edition = "2021"
description = "Foreign function interface for Biodivine/LibBDD"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "staticlib"]


[dependencies]
biodivine-lib-bdd = "0.5.17"
